# Generated by Django 4.2.7 on 2023-11-24 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpeg', upload_to='imgs/')),
                ('back_img', models.ImageField(default='default-back.png', upload_to='back/')),
                ('card_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('card_pin', models.CharField(max_length=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFTCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collections_img', models.ImageField(upload_to='coll_img/')),
                ('collections_back', models.ImageField(upload_to='coll_back/')),
                ('collections_name', models.CharField(max_length=50, unique=True)),
                ('items', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usermodel')),
            ],
            options={
                'verbose_name': 'NFT Collection',
                'verbose_name_plural': 'NFT Collections',
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft_name', models.CharField(max_length=100)),
                ('nft_img', models.ImageField(upload_to='nft/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nftcollections')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usermodel')),
            ],
            options={
                'verbose_name': 'NFT',
                'verbose_name_plural': 'NFT',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nft')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.usermodel')),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boshqa_ega', to='main.usermodel')),
            ],
        ),
    ]
